version: '3'
services:
  job-portal-server:
    container_name: job-portal-server
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - job-portal-db
  job-portal-db:
    container_name: job-portal-db
    image: mysql:5
    ports:
      - '5555:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=workclass