# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_my_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_table',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
