# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_auto_20210109_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_table',
            name='job_id',
        ),
        migrations.AlterField(
            model_name='my_table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
