# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0005_auto_20210109_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_table',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
